# SPDX-FileCopyrightText: 2006-2026, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2026, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

analyze:
  - --enable=performance
  - --enable=bugprone
  - --enable=prefix:clang-diagnostic-shadow
  - --disable=bugprone-easily-swappable-parameters
  - --disable=cert-dcl58-cpp
  - --disable=clang-diagnostic-implicit-int-float-conversion
  - --disable=clang-diagnostic-float-conversion
  - --disable=clang-diagnostic-implicit-int-conversion
  - --disable=bugprone-exception-escape
  - --disable=bugprone-narrowing-conversions
  - --disable=deadcode.DeadStores
  - --skip=${GITHUB_WORKSPACE}/.github/config/codechecker.skip
  - --clean

parse:
  - --export=html
  - --output=./html
  - --skip=${GITHUB_WORKSPACE}/.github/config/codechecker.skip
  - --trim-path-prefix=${GITHUB_WORKSPACE}/
