name: Deploy documentation (https://docs.seqan.de/)

on:
  push:
    branches:
      - main
  # Enables a manual trigger, may run on any branch
  workflow_dispatch:

concurrency:
  group: docs-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  CMAKE_VERSION: 3.16.9
  DOXYGEN_VERSION: 1.9.4
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  deploy_documentation:
    name: Deploy Documentation
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # To reuse scripts
      - name: Checkout SeqAn3
        uses: actions/checkout@v3
        with:
          repository: seqan/seqan3
          ref: df3f29a00543f02cc8cb5e05f40ea8057cf36c5d
          path: seqan3
          fetch-depth: 1
          submodules: false

      - name: Configure APT
        continue-on-error: true
        run: bash ./seqan3/.github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        run: bash ./seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install Doxygen
        run: bash ./seqan3/.github/workflows/scripts/install_doxygen.sh

      - name: Load cached documentation
        uses: actions/cache@v3
        with:
          path: doc-build
          key: ${{ runner.os }}-documentation-${{ env.DOXYGEN_VERSION }}

      - name: Build documentation
        run: |
          mkdir -p doc-build
          cd doc-build
          cmake ../test/documentation
          make download-cppreference-doxygen-web-tag
          ctest . -j 2 --output-on-failure

      - name: Deploy User Documentation
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        with:
          flags: '-azr --delete --timeout=60 --omit-dir-times'
          src: 'doc-build/doc_usr/html/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/main_user'

      - name: Deploy Developer Documentation
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        with:
          flags: '-azr --delete --timeout=60 --omit-dir-times'
          src: 'doc-build/doc_dev/html/'
          dest: '$REMOTE_USER@$REMOTE_HOST:$TARGET/main_dev'
